Data loaded correctly
number of classes 70
Traceback (most recent call last):
  File "/home/disi/ml/intromlproject/training-main.py", line 177, in <module>
    main(config)
  File "/home/disi/ml/intromlproject/training-main.py", line 133, in main
    model = load_checkpoint(model, config['checkpoint'], config['device'])
                            ^^^^^
UnboundLocalError: cannot access local variable 'model' where it is not associated with a value